name: Build docker image

on:
  push:
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: echo "export MOZILLA_VERSION=master" >> $BASH_ENV
      - run: |
          npm install --global --force yarn@$1.22.22
          yarn cache clean && yarn --frozen-lockfile --network-concurrency 1
      - run: .ci/update_version
      # Bundle extensions:
      # - run: npm run bundle
      - run: .ci/docker_build